{
 "title": "Moneypool",
 "time": { "from": "2020-04-30T22:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "query": "SELECT full_name FROM contributors"
   }
  ]
 },
 "panels": [
  {
   "title": "Total per person",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(p.date) as time_sec,\n  p.amount as value,\n  c.full_name as metric\nFROM payments AS p\n  INNER JOIN\n    contributors as c\n  ON p.contributor_id = c.contributor_id\nWHERE $__timeFilter(date)\nORDER BY full_name,date  ASC"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(p.date) as time_sec,\n  p.amount as value,\n  c.full_name as metric\nFROM payments AS p\n  INNER JOIN\n    contributors as c\n  ON p.contributor_id = c.contributor_id\nWHERE $__timeFilter(date)\nORDER BY date ASC"
    }
   ]
  },
  {
   "title": "per month",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(date,'1M',0) as time,\n  sum(p.amount) as value,\n  c.full_name as metric\nFROM payments AS p\n  INNER JOIN\n    contributors as c\n  ON p.contributor_id = c.contributor_id\n  \nWHERE $__timeFilter(date)  \ngroup by time, metric\nORDER BY full_name, time ASC\n"
    }
   ]
  },
  {
   "title": "Last payments",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_FORMAT(p.date, \"%d-%M-%Y\") as Datum,\n  c.full_name as Name,\n  p.amount as Betrag\nFROM payments AS p\n  INNER JOIN\n    contributors as c\n  ON p.contributor_id = c.contributor_id\n  where  c.full_name in ($name) and $__timeFilter(date)\nORDER BY date desc"
    }
   ]
  },
  {
   "title": "per round",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(date,'5d',0) as time,\n  sum(p.amount) as value,\n  c.full_name as metric\nFROM payments AS p\n  INNER JOIN\n    contributors as c\n  ON p.contributor_id = c.contributor_id\n  \nWHERE $__timeFilter(date)  \ngroup by time, metric\nORDER BY full_name, time ASC\n"
    }
   ]
  }
 ]
}